-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "public"."feed_management" add column "status" boolean
--  not null default 'true';
