-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "public"."event_master" add column "recurrance_start_time" timetz
--  null;
